export const business = { name: 'Astonishing Touch', legal: 'Astonishing Touch Home Health & Senior Services L.L.C.', phone: '(314) 479-5673', tel: '+13144795673', afterHours: '(314) 276-4607', email: 'info@astonishingtouchhealthcare.org', address: '10880 Baur Blvd., Suite 103', city: 'Creve Coeur, MO 63132' };
export const services = [
 {id:'respite-care', alt:'A caregiver works on a puzzle with a client while a family member leaves for a break', title:'Respite care', line:'A little breathing room.\nA lot of peace of mind.', image:'service-respite-care', film:'01', desc:'Time to recharge, with support at home for the person you love. Talk with us about respite care that fits your family’s routine.', detail:'Support for family caregivers'},
 {id:'companionship', alt:'A caregiver and client play cards together', title:'Friendly companionship', line:'The simple joy\nof good company.', image:'service-companionship', film:'06', desc:'A familiar conversation. A shared memory. Someone to spend the day with. Meaningful companionship brings connection into everyday life.', detail:'Connection, conversation & company'},
 {id:'personal-care', alt:'A caregiver helps a client put on a cardigan', title:'Personal care', line:'More support.\nStill your independence.', image:'service-personal-care', film:'02', desc:'Thoughtful help with everyday personal routines, built around comfort, dignity and the way you like to do things.', detail:'Everyday support, with respect'},
 {id:'hygiene-assistance', alt:'A caregiver helps a client brush her hair at a bathroom vanity', title:'Hygiene assistance', line:'Dignity in\nevery detail.', image:'service-hygiene-assistance', film:'03', desc:'Sensitive, respectful help with personal hygiene routines. We start with your preferences and focus on helping you feel comfortable.', detail:'Personal routines, thoughtfully supported'},
 {id:'meal-preparation', alt:'A caregiver prepares and serves a meal for a client', title:'Meal planning & preparation', line:'Good food.\nBetter days.', image:'service-meal-preparation', film:'05', desc:'Help planning and preparing meals makes daily life a little easier. Share your preferences with us as we build your personalized care plan.', detail:'A helping hand in the kitchen'},
 {id:'housekeeping', alt:'A caregiver wipes a table and vacuums a rug', title:'Light housekeeping', line:'A home that\nfeels like you.', image:'service-housekeeping', film:'10', desc:'A little help with everyday household tasks can make home feel more manageable. Discuss the light housekeeping support that matters most to you.', detail:'Everyday household support'},
 {id:'laundry', alt:'A caregiver helps with clean laundry and folding clothes', title:'Laundry assistance', line:'Fresh comforts.\nFamiliar routines.', image:'service-laundry', film:'11', desc:'Practical support with laundry helps keep daily routines moving, so there is more room in the day for the things you enjoy.', detail:'Help with the everyday essentials'},
 {id:'medication-reminders', alt:'A caregiver points out a reminder while the client checks his own medication organizer', title:'Medication reminders', line:'A gentle reminder.\nOne less worry.', image:'service-medication-reminders', film:'12', desc:'Friendly reminders to help you follow your existing medication routine. Contact our team to discuss what can be included in your care plan.', detail:'Support for your established routine'},
 {id:'errands', alt:'A caregiver helps a client shop for groceries', title:'Assistance running errands', line:'A helping hand,\nbeyond the front door.', image:'service-errands', film:'08', desc:'Help with everyday errands can keep life moving. Let us know what you need and we will discuss the support available to you.', detail:'Help with everyday errands'}
];
export const faqs = [
 {q:'What kind of care does Astonishing Touch provide?',a:'We provide in-home support with respite care, companionship, personal care, hygiene assistance, meal planning and preparation, light housekeeping, laundry, medication reminders and errands. Your care plan can be tailored to your needs.'},
 {q:'Can we create a care plan around my family’s needs?',a:'Yes. We offer personalized care plans. Tell our team about the routines and everyday support that matter to your family so we can discuss the right services.'},
 {q:'Where is your office?',a:'Our office is at 10880 Baur Blvd., Suite 103, Creve Coeur, MO 63132. Contact us to confirm care availability at your home address.'},
 {q:'How do I get started, and what does care cost?',a:'Call (314) 479-5673 or send a care inquiry. Our team can discuss your needs, service availability and pricing. A website inquiry is not a confirmed care appointment.'},
 {q:'When can I reach the office?',a:'Office hours are Monday through Friday, 9:00 a.m. to 5:00 p.m. The office is closed Saturday and Sunday. The published after-hours number is (314) 276-4607.'}
];

export const directionsUrl='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(business.address+', '+business.city);
