// Shared public service explanations: website pages and assistant grounding.
export const serviceDetails:Record<string,{definition:string;examples:string[];planning:string;question:string;answer:string}>={
'respite-care':{definition:'Respite care gives a family caregiver time away from everyday caregiving while their loved one has support at home.',examples:['Company during a family caregiver’s break','Support with the familiar routines included in the care plan'],planning:'Tell the team when you need a break, the routines that matter and who should be contacted with questions. Confirm visit length and availability directly.',question:'Can respite care fit around my family’s schedule?',answer:'Share the days and times you have in mind. The team can discuss availability and a suitable care plan; this website does not confirm a schedule.'},
'companionship':{definition:'Companionship provides social connection through conversation and shared activities that reflect a person’s interests.',examples:['Conversation, reading and shared memories','Cards, puzzles or a favorite hobby'],planning:'Share the person’s interests and the kind of company they enjoy. Ask which activities can be included in their plan.',question:'How is companionship different from personal care?',answer:'Companionship focuses on company and shared activities. Personal care concerns support with everyday self-care routines. Ask the team which combination fits your needs.'},
'personal-care':{definition:'Personal care is respectful help with everyday self-care routines, shaped around the person’s preferences and comfort.',examples:['Help with dressing routines','Practical personal support discussed in the care plan'],planning:'Describe the routines where help is wanted, while keeping sensitive medical information out of the website form. Confirm specific tasks with staff.',question:'Does personal care mean skilled nursing?',answer:'No. The services described here are everyday supportive care. Do not assume nursing, therapy or other clinical services are included; confirm your needs with the team.'},
'hygiene-assistance':{definition:'Hygiene assistance offers sensitive support with personal hygiene and grooming routines while respecting dignity and preferences.',examples:['Help with grooming and hair care','Support with agreed personal hygiene routines'],planning:'Discuss comfort, privacy and preferences directly with the team. The care plan should identify which tasks can be supported.',question:'Can I discuss personal preferences before care starts?',answer:'Yes. Tell the team what helps you feel comfortable and which routines matter. Specific tasks and arrangements need to be agreed with staff.'},
'meal-preparation':{definition:'Meal planning and preparation provides practical help organizing and preparing everyday meals.',examples:['Planning meals around stated preferences','Preparing and serving an agreed meal'],planning:'Discuss food preferences, kitchen routines and any clinician-provided instructions with staff. Do not use chat for individualized diet advice.',question:'Can meals reflect my preferences?',answer:'Share your preferences when discussing a care plan. Confirm what the team can accommodate; meal preparation does not replace advice from a clinician or dietitian.'},
'housekeeping':{definition:'Light housekeeping provides help with everyday household tasks so familiar living spaces are easier to manage.',examples:['Light surface tidying and wiping','Routine vacuuming discussed with the team'],planning:'Make a short list of the household tasks you want help with. Confirm the scope of light housekeeping rather than assuming deep cleaning or repairs are included.',question:'Is this a deep-cleaning service?',answer:'The listed service is light housekeeping. Ask staff to confirm individual tasks; deep cleaning, repairs and heavy work are not promised by this website.'},
'laundry':{definition:'Laundry assistance is practical help with everyday clothing and linen routines at home.',examples:['Handling clean laundry','Folding and organizing clothes'],planning:'Discuss appliance access, garment instructions and the parts of the laundry routine where support would help.',question:'Can laundry be discussed alongside other support?',answer:'Yes. Tell the team about laundry and any other listed services you need so they can discuss a personalized care plan.'},
'medication-reminders':{definition:'Medication reminders support an existing medication routine by providing a timely reminder; they are not medication administration.',examples:['A reminder to follow the established routine','Encouragement to check an existing personal schedule'],planning:'Confirm the reminder arrangement with staff. Take questions about medicines, doses or side effects to the prescribing clinician or pharmacist.',question:'Will a caregiver change doses or administer medication?',answer:'The service listed here is reminders only. This website does not offer prescribing, dose changes or medication administration.'},
'errands':{definition:'Errand assistance provides practical help with everyday errands discussed in a personalized care plan.',examples:['Help with a grocery-shopping task','Support with agreed everyday errands'],planning:'Tell the team which errands you need help with and ask about arrangements. Do not assume transportation, driving or vehicle provision is included.',question:'Does errand assistance include transportation?',answer:'Transportation arrangements are not confirmed here. Ask staff directly about the errand, location and any travel needs before making plans.'}
};
