import {notFound} from 'next/navigation';
import {business,services} from '../../content';
import {serviceDetails} from '../../service-details';
import {films} from '../../films';
import {absolute} from '../../search-config';
import {SearchShell,JsonLd,organization,organizationId,breadcrumbs} from '../../search-structure';
export function generateStaticParams(){return services.map(s=>({slug:s.id}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(s=>s.id===slug);if(!s)return {title:'Service not found'};return {title:s.title+' | Astonishing Touch, Creve Coeur',description:serviceDetails[slug].definition,alternates:{canonical:absolute('/services/'+slug)},openGraph:{title:s.title+' | Astonishing Touch',description:serviceDetails[slug].definition,url:absolute('/services/'+slug),images:[{url:absolute('/images/'+s.image+'.webp'),alt:s.alt}]}}}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(s=>s.id===slug);if(!s)notFound();const d=serviceDetails[slug];const path='/services/'+slug;const qs=[{q:d.question,a:d.answer},{q:'How do I ask about availability and prices?',a:'Call '+business.phone+' to speak with a live employee about your needs, availability and pricing. An inquiry is not a confirmed appointment.'}];return <SearchShell><JsonLd data={{'@context':'https://schema.org','@graph':[organization,{'@type':'Service','@id':absolute(path+'#service'),name:s.title,description:d.definition,url:absolute(path),provider:{'@id':organizationId}},breadcrumbs([{name:'Home',path:'/'},{name:'Services',path:'/services'},{name:s.title,path}]),{'@type':'FAQPage','@id':absolute(path+'#questions'),mainEntity:qs.map(f=>({'@type':'Question',name:f.q,acceptedAnswer:{'@type':'Answer',text:f.a}}))}]}}/><nav aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/services">Services</a> / {s.title}</nav><p className="eyebrow">CARE AT HOME · CREVE COEUR OFFICE</p><h1>{s.title}</h1><p className="resource-lead">{d.definition}</p><figure><video controls muted loop playsInline preload="none" poster={'/images/'+s.image+'.webp'} aria-label={s.alt}><source src={films[s.film]} type="video/mp4"/></video><figcaption>{s.alt}. Illustrative care scene; specific tasks are agreed with the team.</figcaption></figure><section><h2>What support can look like</h2><ul>{d.examples.map(x=><li key={x}>{x}</li>)}</ul><p>{s.desc}</p></section><section><h2>Planning support around you</h2><p>{d.planning}</p><p>Our office is in Creve Coeur, Missouri. Contact the team to confirm availability at your home address.</p></section><section id="questions"><h2>Your questions</h2>{qs.map(f=><div key={f.q}><h3>{f.q}</h3><p>{f.a}</p></div>)}</section><a className="button" href={'tel:'+business.tel}>Talk with our team · {business.phone}</a><p><a href="/#contact">Send a care inquiry</a> · <a href="/contact">Office details & directions</a></p><section><h2>Explore other support</h2><ul>{services.filter(x=>x.id!==slug).map(x=><li key={x.id}><a href={'/services/'+x.id}>{x.title}</a></li>)}</ul></section></SearchShell>}
